create table emp_id_seq (next_val bigint) engine=InnoDB;
insert into emp_id_seq values ( 1 );
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table images (id bigint not null, image longblob, primary key (id)) engine=InnoDB;
create table ord_id_seq (next_val bigint) engine=InnoDB;
insert into ord_id_seq values ( 1 );
create table orders (order_id bigint not null, creation_date datetime, delivery_date datetime, customer_id bigint not null, employee_id bigint not null, primary key (order_id)) engine=InnoDB;
create table persons (dtype varchar(31) not null, person_id bigint not null, name varchar(255), surname varchar(255), salary decimal(19,2), primary key (person_id)) engine=InnoDB;
create table prod_id_seq (next_val bigint) engine=InnoDB;
insert into prod_id_seq values ( 1 );
create table product_order (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table products (product_id bigint not null, name varchar(255), product_category integer, quantity integer not null, image_id bigint, primary key (product_id)) engine=InnoDB;
alter table orders add constraint FK67o75kfprv9ypqahw4g89mlsk foreign key (customer_id) references persons (person_id);
alter table orders add constraint FKe6dhabg8c0gx3qhsie7a5bq2p foreign key (employee_id) references persons (person_id);
alter table product_order add constraint FK3q4uv0x8kbl98gs6rhjvw60x3 foreign key (product_id) references products (product_id);
alter table product_order add constraint FKjwsik4uvq2sdqtb7x6h1o5f0v foreign key (order_id) references orders (order_id);
alter table products add constraint FKn18ti2byyc5pbjr9cpjj7qkl9 foreign key (image_id) references images (id);
create table customers (person_id bigint not null, primary key (person_id)) engine=InnoDB;
create table emp_id_seq (next_val bigint) engine=InnoDB;
insert into emp_id_seq values ( 1 );
create table employees (salary decimal(19,2), person_id bigint not null, primary key (person_id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table images (id bigint not null, image longblob, primary key (id)) engine=InnoDB;
create table ord_id_seq (next_val bigint) engine=InnoDB;
insert into ord_id_seq values ( 1 );
create table orders (order_id bigint not null, creation_date datetime, delivery_date datetime, customer_id bigint not null, employee_id bigint not null, primary key (order_id)) engine=InnoDB;
create table persons (person_id bigint not null, name varchar(255), surname varchar(255), primary key (person_id)) engine=InnoDB;
create table prod_id_seq (next_val bigint) engine=InnoDB;
insert into prod_id_seq values ( 1 );
create table product_order (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table products (product_id bigint not null, name varchar(255), product_category integer, quantity integer not null, image_id bigint, primary key (product_id)) engine=InnoDB;
alter table customers add constraint FK2wkt5i862ljgauvs6mtjh8d8v foreign key (person_id) references persons (person_id);
alter table employees add constraint FKmde5m6lhciqqdjex9loo2nm0 foreign key (person_id) references persons (person_id);
alter table orders add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references customers (person_id);
alter table orders add constraint FKfhl8bv0xn3sj33q2f3scf1bq6 foreign key (employee_id) references employees (person_id);
alter table product_order add constraint FK3q4uv0x8kbl98gs6rhjvw60x3 foreign key (product_id) references products (product_id);
alter table product_order add constraint FKjwsik4uvq2sdqtb7x6h1o5f0v foreign key (order_id) references orders (order_id);
alter table products add constraint FKn18ti2byyc5pbjr9cpjj7qkl9 foreign key (image_id) references images (id);
